/**
 * Stardust API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023-06-15T19:52:41Z
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "OAISDTemplateCreateResponse.h"

#include <QDebug>
#include <QJsonArray>
#include <QJsonDocument>
#include <QObject>

#include "OAIHelpers.h"

namespace stardust {
namespace core {

OAISDTemplateCreateResponse::OAISDTemplateCreateResponse(QString json) {
    this->initializeModel();
    this->fromJson(json);
}

OAISDTemplateCreateResponse::OAISDTemplateCreateResponse() {
    this->initializeModel();
}

OAISDTemplateCreateResponse::~OAISDTemplateCreateResponse() {}

void OAISDTemplateCreateResponse::initializeModel() {

    m_id_isSet = false;
    m_id_isValid = false;
}

void OAISDTemplateCreateResponse::fromJson(QString jsonString) {
    QByteArray array(jsonString.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
}

void OAISDTemplateCreateResponse::fromJsonObject(QJsonObject json) {

    m_id_isValid = ::stardust::core::fromJsonValue(id, json[QString("id")]);
    m_id_isSet = !json[QString("id")].isNull() && m_id_isValid;
}

QString OAISDTemplateCreateResponse::asJson() const {
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject OAISDTemplateCreateResponse::asJsonObject() const {
    QJsonObject obj;
    if (m_id_isSet) {
        obj.insert(QString("id"), ::stardust::core::toJsonValue(id));
    }
    return obj;
}

qint32 OAISDTemplateCreateResponse::getId() const {
    return id;
}
void OAISDTemplateCreateResponse::setId(const qint32 &id) {
    this->id = id;
    this->m_id_isSet = true;
}

bool OAISDTemplateCreateResponse::is_id_Set() const{
    return m_id_isSet;
}

bool OAISDTemplateCreateResponse::is_id_Valid() const{
    return m_id_isValid;
}

bool OAISDTemplateCreateResponse::isSet() const {
    bool isObjectUpdated = false;
    do {
        if (m_id_isSet) {
            isObjectUpdated = true;
            break;
        }
    } while (false);
    return isObjectUpdated;
}

bool OAISDTemplateCreateResponse::isValid() const {
    // only required properties are required for the object to be considered valid
    return true;
}

} // namespace stardust
} // namespace core
