/**
 * Stardust API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023-07-25T00:59:12Z
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAISDTemplateGetTokensResponse_player.h
 *
 * 
 */

#ifndef OAISDTemplateGetTokensResponse_player_H
#define OAISDTemplateGetTokensResponse_player_H

#include <QJsonObject>

#include <QString>

#include "OAIEnum.h"
#include "OAIObject.h"

namespace stardust {
namespace core {

class OAISDTemplateGetTokensResponse_player : public OAIObject {
public:
    OAISDTemplateGetTokensResponse_player();
    OAISDTemplateGetTokensResponse_player(QString json);
    ~OAISDTemplateGetTokensResponse_player() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    QString getId() const;
    void setId(const QString &id);
    bool is_id_Set() const;
    bool is_id_Valid() const;

    QString getUniqueId() const;
    void setUniqueId(const QString &unique_id);
    bool is_unique_id_Set() const;
    bool is_unique_id_Valid() const;

    QString getImage() const;
    void setImage(const QString &image);
    bool is_image_Set() const;
    bool is_image_Valid() const;

    QString getDeletedAt() const;
    void setDeletedAt(const QString &deleted_at);
    bool is_deleted_at_Set() const;
    bool is_deleted_at_Valid() const;

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();

    QString id;
    bool m_id_isSet;
    bool m_id_isValid;

    QString unique_id;
    bool m_unique_id_isSet;
    bool m_unique_id_isValid;

    QString image;
    bool m_image_isSet;
    bool m_image_isValid;

    QString deleted_at;
    bool m_deleted_at_isSet;
    bool m_deleted_at_isValid;
};

} // namespace stardust
} // namespace core

Q_DECLARE_METATYPE(stardust::core::OAISDTemplateGetTokensResponse_player)

#endif // OAISDTemplateGetTokensResponse_player_H
