/**
 * Stardust API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023-06-15T19:52:41Z
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAISDPlayerCreateResponse.h
 *
 * The id of the player created
 */

#ifndef OAISDPlayerCreateResponse_H
#define OAISDPlayerCreateResponse_H

#include <QJsonObject>

#include <QString>

#include "OAIEnum.h"
#include "OAIObject.h"

namespace stardust {
namespace core {

class OAISDPlayerCreateResponse : public OAIObject {
public:
    OAISDPlayerCreateResponse();
    OAISDPlayerCreateResponse(QString json);
    ~OAISDPlayerCreateResponse() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    QString getPlayerId() const;
    void setPlayerId(const QString &player_id);
    bool is_player_id_Set() const;
    bool is_player_id_Valid() const;

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();

    QString player_id;
    bool m_player_id_isSet;
    bool m_player_id_isValid;
};

} // namespace stardust
} // namespace core

Q_DECLARE_METATYPE(stardust::core::OAISDPlayerCreateResponse)

#endif // OAISDPlayerCreateResponse_H
