/**
 * Stardust API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023-07-25T00:59:12Z
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAISDPlayerGetIdsResponse.h
 *
 * This is the data output json model, i.e. {\&quot;uniqueId\&quot;: \&quot;playerId\&quot;} 
 */

#ifndef OAISDPlayerGetIdsResponse_H
#define OAISDPlayerGetIdsResponse_H

#include <QJsonObject>

#include <QString>

#include "OAIEnum.h"
#include "OAIObject.h"

namespace stardust {
namespace core {

class OAISDPlayerGetIdsResponse : public OAIObject {
public:
    OAISDPlayerGetIdsResponse();
    OAISDPlayerGetIdsResponse(QString json);
    ~OAISDPlayerGetIdsResponse() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    QString getPlayerId() const;
    void setPlayerId(const QString &player_id);
    bool is_player_id_Set() const;
    bool is_player_id_Valid() const;

    QString getUniqueId() const;
    void setUniqueId(const QString &unique_id);
    bool is_unique_id_Set() const;
    bool is_unique_id_Valid() const;

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();

    QString player_id;
    bool m_player_id_isSet;
    bool m_player_id_isValid;

    QString unique_id;
    bool m_unique_id_isSet;
    bool m_unique_id_isValid;
};

} // namespace stardust
} // namespace core

Q_DECLARE_METATYPE(stardust::core::OAISDPlayerGetIdsResponse)

#endif // OAISDPlayerGetIdsResponse_H
