/**
 * Stardust API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023-07-25T00:59:12Z
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAISDPlayerWalletGetResponse.h
 *
 * This is the data output json model
 */

#ifndef OAISDPlayerWalletGetResponse_H
#define OAISDPlayerWalletGetResponse_H

#include <QJsonObject>

#include "OAISDPlayerWalletGetResponse_wallet_inner.h"
#include <QList>

#include "OAIEnum.h"
#include "OAIObject.h"

namespace stardust {
namespace core {
class OAISDPlayerWalletGetResponse_wallet_inner;

class OAISDPlayerWalletGetResponse : public OAIObject {
public:
    OAISDPlayerWalletGetResponse();
    OAISDPlayerWalletGetResponse(QString json);
    ~OAISDPlayerWalletGetResponse() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    QList<OAISDPlayerWalletGetResponse_wallet_inner> getWallet() const;
    void setWallet(const QList<OAISDPlayerWalletGetResponse_wallet_inner> &wallet);
    bool is_wallet_Set() const;
    bool is_wallet_Valid() const;

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();

    QList<OAISDPlayerWalletGetResponse_wallet_inner> wallet;
    bool m_wallet_isSet;
    bool m_wallet_isValid;
};

} // namespace stardust
} // namespace core

Q_DECLARE_METATYPE(stardust::core::OAISDPlayerWalletGetResponse)

#endif // OAISDPlayerWalletGetResponse_H
