/**
 * Stardust API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023-07-25T00:59:12Z
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "OAISDTokenMutateRequest.h"

#include <QDebug>
#include <QJsonArray>
#include <QJsonDocument>
#include <QObject>

#include "OAIHelpers.h"

namespace stardust {
namespace core {

OAISDTokenMutateRequest::OAISDTokenMutateRequest(QString json) {
    this->initializeModel();
    this->fromJson(json);
}

OAISDTokenMutateRequest::OAISDTokenMutateRequest() {
    this->initializeModel();
}

OAISDTokenMutateRequest::~OAISDTokenMutateRequest() {}

void OAISDTokenMutateRequest::initializeModel() {

    m_token_id_isSet = false;
    m_token_id_isValid = false;

    m_props_isSet = false;
    m_props_isValid = false;

    m_public_metadata_isSet = false;
    m_public_metadata_isValid = false;
}

void OAISDTokenMutateRequest::fromJson(QString jsonString) {
    QByteArray array(jsonString.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
}

void OAISDTokenMutateRequest::fromJsonObject(QJsonObject json) {

    m_token_id_isValid = ::stardust::core::fromJsonValue(token_id, json[QString("tokenId")]);
    m_token_id_isSet = !json[QString("tokenId")].isNull() && m_token_id_isValid;

    m_props_isValid = ::stardust::core::fromJsonValue(props, json[QString("props")]);
    m_props_isSet = !json[QString("props")].isNull() && m_props_isValid;

    m_public_metadata_isValid = ::stardust::core::fromJsonValue(public_metadata, json[QString("publicMetadata")]);
    m_public_metadata_isSet = !json[QString("publicMetadata")].isNull() && m_public_metadata_isValid;
}

QString OAISDTokenMutateRequest::asJson() const {
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject OAISDTokenMutateRequest::asJsonObject() const {
    QJsonObject obj;
    if (m_token_id_isSet) {
        obj.insert(QString("tokenId"), ::stardust::core::toJsonValue(token_id));
    }
    if (m_props_isSet) {
        obj.insert(QString("props"), ::stardust::core::toJsonValue(props));
    }
    if (m_public_metadata_isSet) {
        obj.insert(QString("publicMetadata"), ::stardust::core::toJsonValue(public_metadata));
    }
    return obj;
}

qint32 OAISDTokenMutateRequest::getTokenId() const {
    return token_id;
}
void OAISDTokenMutateRequest::setTokenId(const qint32 &token_id) {
    this->token_id = token_id;
    this->m_token_id_isSet = true;
}

bool OAISDTokenMutateRequest::is_token_id_Set() const{
    return m_token_id_isSet;
}

bool OAISDTokenMutateRequest::is_token_id_Valid() const{
    return m_token_id_isValid;
}

OAIObject OAISDTokenMutateRequest::getProps() const {
    return props;
}
void OAISDTokenMutateRequest::setProps(const OAIObject &props) {
    this->props = props;
    this->m_props_isSet = true;
}

bool OAISDTokenMutateRequest::is_props_Set() const{
    return m_props_isSet;
}

bool OAISDTokenMutateRequest::is_props_Valid() const{
    return m_props_isValid;
}

OAIObject OAISDTokenMutateRequest::getPublicMetadata() const {
    return public_metadata;
}
void OAISDTokenMutateRequest::setPublicMetadata(const OAIObject &public_metadata) {
    this->public_metadata = public_metadata;
    this->m_public_metadata_isSet = true;
}

bool OAISDTokenMutateRequest::is_public_metadata_Set() const{
    return m_public_metadata_isSet;
}

bool OAISDTokenMutateRequest::is_public_metadata_Valid() const{
    return m_public_metadata_isValid;
}

bool OAISDTokenMutateRequest::isSet() const {
    bool isObjectUpdated = false;
    do {
        if (m_token_id_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_props_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_public_metadata_isSet) {
            isObjectUpdated = true;
            break;
        }
    } while (false);
    return isObjectUpdated;
}

bool OAISDTokenMutateRequest::isValid() const {
    // only required properties are required for the object to be considered valid
    return m_token_id_isValid && m_props_isValid && true;
}

} // namespace stardust
} // namespace core
