/**
 * Stardust API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023-06-15T19:52:41Z
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "OAISDPlayerWalletGetResponse.h"

#include <QDebug>
#include <QJsonArray>
#include <QJsonDocument>
#include <QObject>

#include "OAIHelpers.h"

namespace stardust {
namespace core {

OAISDPlayerWalletGetResponse::OAISDPlayerWalletGetResponse(QString json) {
    this->initializeModel();
    this->fromJson(json);
}

OAISDPlayerWalletGetResponse::OAISDPlayerWalletGetResponse() {
    this->initializeModel();
}

OAISDPlayerWalletGetResponse::~OAISDPlayerWalletGetResponse() {}

void OAISDPlayerWalletGetResponse::initializeModel() {

    m_wallet_isSet = false;
    m_wallet_isValid = false;
}

void OAISDPlayerWalletGetResponse::fromJson(QString jsonString) {
    QByteArray array(jsonString.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
}

void OAISDPlayerWalletGetResponse::fromJsonObject(QJsonObject json) {

    m_wallet_isValid = ::stardust::core::fromJsonValue(wallet, json[QString("wallet")]);
    m_wallet_isSet = !json[QString("wallet")].isNull() && m_wallet_isValid;
}

QString OAISDPlayerWalletGetResponse::asJson() const {
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject OAISDPlayerWalletGetResponse::asJsonObject() const {
    QJsonObject obj;
    if (wallet.size() > 0) {
        obj.insert(QString("wallet"), ::stardust::core::toJsonValue(wallet));
    }
    return obj;
}

QList<OAISDPlayerWalletGetResponse_wallet_inner> OAISDPlayerWalletGetResponse::getWallet() const {
    return wallet;
}
void OAISDPlayerWalletGetResponse::setWallet(const QList<OAISDPlayerWalletGetResponse_wallet_inner> &wallet) {
    this->wallet = wallet;
    this->m_wallet_isSet = true;
}

bool OAISDPlayerWalletGetResponse::is_wallet_Set() const{
    return m_wallet_isSet;
}

bool OAISDPlayerWalletGetResponse::is_wallet_Valid() const{
    return m_wallet_isValid;
}

bool OAISDPlayerWalletGetResponse::isSet() const {
    bool isObjectUpdated = false;
    do {
        if (wallet.size() > 0) {
            isObjectUpdated = true;
            break;
        }
    } while (false);
    return isObjectUpdated;
}

bool OAISDPlayerWalletGetResponse::isValid() const {
    // only required properties are required for the object to be considered valid
    return m_wallet_isValid && true;
}

} // namespace stardust
} // namespace core
