/**
 * Stardust API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023-06-15T19:52:41Z
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "OAISDPlayerGetAllResponse.h"

#include <QDebug>
#include <QJsonArray>
#include <QJsonDocument>
#include <QObject>

#include "OAIHelpers.h"

namespace stardust {
namespace core {

OAISDPlayerGetAllResponse::OAISDPlayerGetAllResponse(QString json) {
    this->initializeModel();
    this->fromJson(json);
}

OAISDPlayerGetAllResponse::OAISDPlayerGetAllResponse() {
    this->initializeModel();
}

OAISDPlayerGetAllResponse::~OAISDPlayerGetAllResponse() {}

void OAISDPlayerGetAllResponse::initializeModel() {

    m_player_id_isSet = false;
    m_player_id_isValid = false;

    m_unique_id_isSet = false;
    m_unique_id_isValid = false;

    m_id_isSet = false;
    m_id_isValid = false;

    m_last_seen_isSet = false;
    m_last_seen_isValid = false;

    m_image_isSet = false;
    m_image_isValid = false;
}

void OAISDPlayerGetAllResponse::fromJson(QString jsonString) {
    QByteArray array(jsonString.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
}

void OAISDPlayerGetAllResponse::fromJsonObject(QJsonObject json) {

    m_player_id_isValid = ::stardust::core::fromJsonValue(player_id, json[QString("playerId")]);
    m_player_id_isSet = !json[QString("playerId")].isNull() && m_player_id_isValid;

    m_unique_id_isValid = ::stardust::core::fromJsonValue(unique_id, json[QString("uniqueId")]);
    m_unique_id_isSet = !json[QString("uniqueId")].isNull() && m_unique_id_isValid;

    m_id_isValid = ::stardust::core::fromJsonValue(id, json[QString("id")]);
    m_id_isSet = !json[QString("id")].isNull() && m_id_isValid;

    m_last_seen_isValid = ::stardust::core::fromJsonValue(last_seen, json[QString("lastSeen")]);
    m_last_seen_isSet = !json[QString("lastSeen")].isNull() && m_last_seen_isValid;

    m_image_isValid = ::stardust::core::fromJsonValue(image, json[QString("image")]);
    m_image_isSet = !json[QString("image")].isNull() && m_image_isValid;
}

QString OAISDPlayerGetAllResponse::asJson() const {
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject OAISDPlayerGetAllResponse::asJsonObject() const {
    QJsonObject obj;
    if (m_player_id_isSet) {
        obj.insert(QString("playerId"), ::stardust::core::toJsonValue(player_id));
    }
    if (m_unique_id_isSet) {
        obj.insert(QString("uniqueId"), ::stardust::core::toJsonValue(unique_id));
    }
    if (m_id_isSet) {
        obj.insert(QString("id"), ::stardust::core::toJsonValue(id));
    }
    if (m_last_seen_isSet) {
        obj.insert(QString("lastSeen"), ::stardust::core::toJsonValue(last_seen));
    }
    if (m_image_isSet) {
        obj.insert(QString("image"), ::stardust::core::toJsonValue(image));
    }
    return obj;
}

QString OAISDPlayerGetAllResponse::getPlayerId() const {
    return player_id;
}
void OAISDPlayerGetAllResponse::setPlayerId(const QString &player_id) {
    this->player_id = player_id;
    this->m_player_id_isSet = true;
}

bool OAISDPlayerGetAllResponse::is_player_id_Set() const{
    return m_player_id_isSet;
}

bool OAISDPlayerGetAllResponse::is_player_id_Valid() const{
    return m_player_id_isValid;
}

QString OAISDPlayerGetAllResponse::getUniqueId() const {
    return unique_id;
}
void OAISDPlayerGetAllResponse::setUniqueId(const QString &unique_id) {
    this->unique_id = unique_id;
    this->m_unique_id_isSet = true;
}

bool OAISDPlayerGetAllResponse::is_unique_id_Set() const{
    return m_unique_id_isSet;
}

bool OAISDPlayerGetAllResponse::is_unique_id_Valid() const{
    return m_unique_id_isValid;
}

double OAISDPlayerGetAllResponse::getId() const {
    return id;
}
void OAISDPlayerGetAllResponse::setId(const double &id) {
    this->id = id;
    this->m_id_isSet = true;
}

bool OAISDPlayerGetAllResponse::is_id_Set() const{
    return m_id_isSet;
}

bool OAISDPlayerGetAllResponse::is_id_Valid() const{
    return m_id_isValid;
}

QString OAISDPlayerGetAllResponse::getLastSeen() const {
    return last_seen;
}
void OAISDPlayerGetAllResponse::setLastSeen(const QString &last_seen) {
    this->last_seen = last_seen;
    this->m_last_seen_isSet = true;
}

bool OAISDPlayerGetAllResponse::is_last_seen_Set() const{
    return m_last_seen_isSet;
}

bool OAISDPlayerGetAllResponse::is_last_seen_Valid() const{
    return m_last_seen_isValid;
}

QString OAISDPlayerGetAllResponse::getImage() const {
    return image;
}
void OAISDPlayerGetAllResponse::setImage(const QString &image) {
    this->image = image;
    this->m_image_isSet = true;
}

bool OAISDPlayerGetAllResponse::is_image_Set() const{
    return m_image_isSet;
}

bool OAISDPlayerGetAllResponse::is_image_Valid() const{
    return m_image_isValid;
}

bool OAISDPlayerGetAllResponse::isSet() const {
    bool isObjectUpdated = false;
    do {
        if (m_player_id_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_unique_id_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_id_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_last_seen_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_image_isSet) {
            isObjectUpdated = true;
            break;
        }
    } while (false);
    return isObjectUpdated;
}

bool OAISDPlayerGetAllResponse::isValid() const {
    // only required properties are required for the object to be considered valid
    return m_player_id_isValid && m_unique_id_isValid && true;
}

} // namespace stardust
} // namespace core
