/**
 * Stardust API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023-06-15T19:52:41Z
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAISDOrderBuyRequest.h
 *
 * 
 */

#ifndef OAISDOrderBuyRequest_H
#define OAISDOrderBuyRequest_H

#include <QJsonObject>

#include <QString>

#include "OAIEnum.h"
#include "OAIObject.h"

namespace stardust {
namespace core {

class OAISDOrderBuyRequest : public OAIObject {
public:
    OAISDOrderBuyRequest();
    OAISDOrderBuyRequest(QString json);
    ~OAISDOrderBuyRequest() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    qint32 getOrderId() const;
    void setOrderId(const qint32 &order_id);
    bool is_order_id_Set() const;
    bool is_order_id_Valid() const;

    QString getAcceptedBy() const;
    void setAcceptedBy(const QString &accepted_by);
    bool is_accepted_by_Set() const;
    bool is_accepted_by_Valid() const;

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();

    qint32 order_id;
    bool m_order_id_isSet;
    bool m_order_id_isValid;

    QString accepted_by;
    bool m_accepted_by_isSet;
    bool m_accepted_by_isValid;
};

} // namespace stardust
} // namespace core

Q_DECLARE_METATYPE(stardust::core::OAISDOrderBuyRequest)

#endif // OAISDOrderBuyRequest_H
