/**
 * Stardust API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023-07-25T00:59:12Z
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAISDTemplateMutateRequest.h
 *
 * 
 */

#ifndef OAISDTemplateMutateRequest_H
#define OAISDTemplateMutateRequest_H

#include <QJsonObject>

#include "OAIObject.h"

#include "OAIEnum.h"
#include "OAIObject.h"

namespace stardust {
namespace core {

class OAISDTemplateMutateRequest : public OAIObject {
public:
    OAISDTemplateMutateRequest();
    OAISDTemplateMutateRequest(QString json);
    ~OAISDTemplateMutateRequest() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    qint32 getTemplateId() const;
    void setTemplateId(const qint32 &template_id);
    bool is_template_id_Set() const;
    bool is_template_id_Valid() const;

    OAIObject getProps() const;
    void setProps(const OAIObject &props);
    bool is_props_Set() const;
    bool is_props_Valid() const;

    OAIObject getPublicContractMetadata() const;
    void setPublicContractMetadata(const OAIObject &public_contract_metadata);
    bool is_public_contract_metadata_Set() const;
    bool is_public_contract_metadata_Valid() const;

    OAIObject getPublicTokenMetadata() const;
    void setPublicTokenMetadata(const OAIObject &public_token_metadata);
    bool is_public_token_metadata_Set() const;
    bool is_public_token_metadata_Valid() const;

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();

    qint32 template_id;
    bool m_template_id_isSet;
    bool m_template_id_isValid;

    OAIObject props;
    bool m_props_isSet;
    bool m_props_isValid;

    OAIObject public_contract_metadata;
    bool m_public_contract_metadata_isSet;
    bool m_public_contract_metadata_isValid;

    OAIObject public_token_metadata;
    bool m_public_token_metadata_isSet;
    bool m_public_token_metadata_isValid;
};

} // namespace stardust
} // namespace core

Q_DECLARE_METATYPE(stardust::core::OAISDTemplateMutateRequest)

#endif // OAISDTemplateMutateRequest_H
