/**
 * Stardust API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023-07-25T00:59:12Z
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "OAISDTemplateCreateBulk.h"

#include <QDebug>
#include <QJsonArray>
#include <QJsonDocument>
#include <QObject>

#include "OAIHelpers.h"

namespace stardust {
namespace core {

OAISDTemplateCreateBulk::OAISDTemplateCreateBulk(QString json) {
    this->initializeModel();
    this->fromJson(json);
}

OAISDTemplateCreateBulk::OAISDTemplateCreateBulk() {
    this->initializeModel();
}

OAISDTemplateCreateBulk::~OAISDTemplateCreateBulk() {}

void OAISDTemplateCreateBulk::initializeModel() {

    m_name_isSet = false;
    m_name_isValid = false;

    m_cap_isSet = false;
    m_cap_isValid = false;

    m_contract_type_isSet = false;
    m_contract_type_isValid = false;

    m_type_isSet = false;
    m_type_isValid = false;

    m_image_isSet = false;
    m_image_isValid = false;

    m_description_isSet = false;
    m_description_isValid = false;

    m_active_listing_isSet = false;
    m_active_listing_isValid = false;

    m_owner_address_isSet = false;
    m_owner_address_isValid = false;

    m_props_isSet = false;
    m_props_isValid = false;

    m_public_contract_metadata_isSet = false;
    m_public_contract_metadata_isValid = false;

    m_public_token_metadata_isSet = false;
    m_public_token_metadata_isValid = false;
}

void OAISDTemplateCreateBulk::fromJson(QString jsonString) {
    QByteArray array(jsonString.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
}

void OAISDTemplateCreateBulk::fromJsonObject(QJsonObject json) {

    m_name_isValid = ::stardust::core::fromJsonValue(name, json[QString("name")]);
    m_name_isSet = !json[QString("name")].isNull() && m_name_isValid;

    m_cap_isValid = ::stardust::core::fromJsonValue(cap, json[QString("cap")]);
    m_cap_isSet = !json[QString("cap")].isNull() && m_cap_isValid;

    m_contract_type_isValid = ::stardust::core::fromJsonValue(contract_type, json[QString("contractType")]);
    m_contract_type_isSet = !json[QString("contractType")].isNull() && m_contract_type_isValid;

    m_type_isValid = ::stardust::core::fromJsonValue(type, json[QString("type")]);
    m_type_isSet = !json[QString("type")].isNull() && m_type_isValid;

    m_image_isValid = ::stardust::core::fromJsonValue(image, json[QString("image")]);
    m_image_isSet = !json[QString("image")].isNull() && m_image_isValid;

    m_description_isValid = ::stardust::core::fromJsonValue(description, json[QString("description")]);
    m_description_isSet = !json[QString("description")].isNull() && m_description_isValid;

    m_active_listing_isValid = ::stardust::core::fromJsonValue(active_listing, json[QString("activeListing")]);
    m_active_listing_isSet = !json[QString("activeListing")].isNull() && m_active_listing_isValid;

    m_owner_address_isValid = ::stardust::core::fromJsonValue(owner_address, json[QString("ownerAddress")]);
    m_owner_address_isSet = !json[QString("ownerAddress")].isNull() && m_owner_address_isValid;

    m_props_isValid = ::stardust::core::fromJsonValue(props, json[QString("props")]);
    m_props_isSet = !json[QString("props")].isNull() && m_props_isValid;

    m_public_contract_metadata_isValid = ::stardust::core::fromJsonValue(public_contract_metadata, json[QString("publicContractMetadata")]);
    m_public_contract_metadata_isSet = !json[QString("publicContractMetadata")].isNull() && m_public_contract_metadata_isValid;

    m_public_token_metadata_isValid = ::stardust::core::fromJsonValue(public_token_metadata, json[QString("publicTokenMetadata")]);
    m_public_token_metadata_isSet = !json[QString("publicTokenMetadata")].isNull() && m_public_token_metadata_isValid;
}

QString OAISDTemplateCreateBulk::asJson() const {
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject OAISDTemplateCreateBulk::asJsonObject() const {
    QJsonObject obj;
    if (m_name_isSet) {
        obj.insert(QString("name"), ::stardust::core::toJsonValue(name));
    }
    if (m_cap_isSet) {
        obj.insert(QString("cap"), ::stardust::core::toJsonValue(cap));
    }
    if (m_contract_type_isSet) {
        obj.insert(QString("contractType"), ::stardust::core::toJsonValue(contract_type));
    }
    if (m_type_isSet) {
        obj.insert(QString("type"), ::stardust::core::toJsonValue(type));
    }
    if (m_image_isSet) {
        obj.insert(QString("image"), ::stardust::core::toJsonValue(image));
    }
    if (m_description_isSet) {
        obj.insert(QString("description"), ::stardust::core::toJsonValue(description));
    }
    if (m_active_listing_isSet) {
        obj.insert(QString("activeListing"), ::stardust::core::toJsonValue(active_listing));
    }
    if (m_owner_address_isSet) {
        obj.insert(QString("ownerAddress"), ::stardust::core::toJsonValue(owner_address));
    }
    if (props.isSet()) {
        obj.insert(QString("props"), ::stardust::core::toJsonValue(props));
    }
    if (m_public_contract_metadata_isSet) {
        obj.insert(QString("publicContractMetadata"), ::stardust::core::toJsonValue(public_contract_metadata));
    }
    if (m_public_token_metadata_isSet) {
        obj.insert(QString("publicTokenMetadata"), ::stardust::core::toJsonValue(public_token_metadata));
    }
    return obj;
}

QString OAISDTemplateCreateBulk::getName() const {
    return name;
}
void OAISDTemplateCreateBulk::setName(const QString &name) {
    this->name = name;
    this->m_name_isSet = true;
}

bool OAISDTemplateCreateBulk::is_name_Set() const{
    return m_name_isSet;
}

bool OAISDTemplateCreateBulk::is_name_Valid() const{
    return m_name_isValid;
}

QString OAISDTemplateCreateBulk::getCap() const {
    return cap;
}
void OAISDTemplateCreateBulk::setCap(const QString &cap) {
    this->cap = cap;
    this->m_cap_isSet = true;
}

bool OAISDTemplateCreateBulk::is_cap_Set() const{
    return m_cap_isSet;
}

bool OAISDTemplateCreateBulk::is_cap_Valid() const{
    return m_cap_isValid;
}

QString OAISDTemplateCreateBulk::getContractType() const {
    return contract_type;
}
void OAISDTemplateCreateBulk::setContractType(const QString &contract_type) {
    this->contract_type = contract_type;
    this->m_contract_type_isSet = true;
}

bool OAISDTemplateCreateBulk::is_contract_type_Set() const{
    return m_contract_type_isSet;
}

bool OAISDTemplateCreateBulk::is_contract_type_Valid() const{
    return m_contract_type_isValid;
}

QString OAISDTemplateCreateBulk::getType() const {
    return type;
}
void OAISDTemplateCreateBulk::setType(const QString &type) {
    this->type = type;
    this->m_type_isSet = true;
}

bool OAISDTemplateCreateBulk::is_type_Set() const{
    return m_type_isSet;
}

bool OAISDTemplateCreateBulk::is_type_Valid() const{
    return m_type_isValid;
}

QString OAISDTemplateCreateBulk::getImage() const {
    return image;
}
void OAISDTemplateCreateBulk::setImage(const QString &image) {
    this->image = image;
    this->m_image_isSet = true;
}

bool OAISDTemplateCreateBulk::is_image_Set() const{
    return m_image_isSet;
}

bool OAISDTemplateCreateBulk::is_image_Valid() const{
    return m_image_isValid;
}

QString OAISDTemplateCreateBulk::getDescription() const {
    return description;
}
void OAISDTemplateCreateBulk::setDescription(const QString &description) {
    this->description = description;
    this->m_description_isSet = true;
}

bool OAISDTemplateCreateBulk::is_description_Set() const{
    return m_description_isSet;
}

bool OAISDTemplateCreateBulk::is_description_Valid() const{
    return m_description_isValid;
}

bool OAISDTemplateCreateBulk::isActiveListing() const {
    return active_listing;
}
void OAISDTemplateCreateBulk::setActiveListing(const bool &active_listing) {
    this->active_listing = active_listing;
    this->m_active_listing_isSet = true;
}

bool OAISDTemplateCreateBulk::is_active_listing_Set() const{
    return m_active_listing_isSet;
}

bool OAISDTemplateCreateBulk::is_active_listing_Valid() const{
    return m_active_listing_isValid;
}

QString OAISDTemplateCreateBulk::getOwnerAddress() const {
    return owner_address;
}
void OAISDTemplateCreateBulk::setOwnerAddress(const QString &owner_address) {
    this->owner_address = owner_address;
    this->m_owner_address_isSet = true;
}

bool OAISDTemplateCreateBulk::is_owner_address_Set() const{
    return m_owner_address_isSet;
}

bool OAISDTemplateCreateBulk::is_owner_address_Valid() const{
    return m_owner_address_isValid;
}

OAISDTemplateCreateBulk_props OAISDTemplateCreateBulk::getProps() const {
    return props;
}
void OAISDTemplateCreateBulk::setProps(const OAISDTemplateCreateBulk_props &props) {
    this->props = props;
    this->m_props_isSet = true;
}

bool OAISDTemplateCreateBulk::is_props_Set() const{
    return m_props_isSet;
}

bool OAISDTemplateCreateBulk::is_props_Valid() const{
    return m_props_isValid;
}

OAIObject OAISDTemplateCreateBulk::getPublicContractMetadata() const {
    return public_contract_metadata;
}
void OAISDTemplateCreateBulk::setPublicContractMetadata(const OAIObject &public_contract_metadata) {
    this->public_contract_metadata = public_contract_metadata;
    this->m_public_contract_metadata_isSet = true;
}

bool OAISDTemplateCreateBulk::is_public_contract_metadata_Set() const{
    return m_public_contract_metadata_isSet;
}

bool OAISDTemplateCreateBulk::is_public_contract_metadata_Valid() const{
    return m_public_contract_metadata_isValid;
}

OAIObject OAISDTemplateCreateBulk::getPublicTokenMetadata() const {
    return public_token_metadata;
}
void OAISDTemplateCreateBulk::setPublicTokenMetadata(const OAIObject &public_token_metadata) {
    this->public_token_metadata = public_token_metadata;
    this->m_public_token_metadata_isSet = true;
}

bool OAISDTemplateCreateBulk::is_public_token_metadata_Set() const{
    return m_public_token_metadata_isSet;
}

bool OAISDTemplateCreateBulk::is_public_token_metadata_Valid() const{
    return m_public_token_metadata_isValid;
}

bool OAISDTemplateCreateBulk::isSet() const {
    bool isObjectUpdated = false;
    do {
        if (m_name_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_cap_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_contract_type_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_type_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_image_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_description_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_active_listing_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_owner_address_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (props.isSet()) {
            isObjectUpdated = true;
            break;
        }

        if (m_public_contract_metadata_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_public_token_metadata_isSet) {
            isObjectUpdated = true;
            break;
        }
    } while (false);
    return isObjectUpdated;
}

bool OAISDTemplateCreateBulk::isValid() const {
    // only required properties are required for the object to be considered valid
    return m_name_isValid && m_image_isValid && true;
}

} // namespace stardust
} // namespace core
