/**
 * Stardust API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023-07-25T00:59:12Z
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAISDPlayerCreateRequest.h
 *
 * 
 */

#ifndef OAISDPlayerCreateRequest_H
#define OAISDPlayerCreateRequest_H

#include <QJsonObject>

#include "OAIObject.h"
#include <QString>

#include "OAIEnum.h"
#include "OAIObject.h"

namespace stardust {
namespace core {

class OAISDPlayerCreateRequest : public OAIObject {
public:
    OAISDPlayerCreateRequest();
    OAISDPlayerCreateRequest(QString json);
    ~OAISDPlayerCreateRequest() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    QString getUniqueId() const;
    void setUniqueId(const QString &unique_id);
    bool is_unique_id_Set() const;
    bool is_unique_id_Valid() const;

    QString getImage() const;
    void setImage(const QString &image);
    bool is_image_Set() const;
    bool is_image_Valid() const;

    OAIObject getUserData() const;
    void setUserData(const OAIObject &user_data);
    bool is_user_data_Set() const;
    bool is_user_data_Valid() const;

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();

    QString unique_id;
    bool m_unique_id_isSet;
    bool m_unique_id_isValid;

    QString image;
    bool m_image_isSet;
    bool m_image_isValid;

    OAIObject user_data;
    bool m_user_data_isSet;
    bool m_user_data_isValid;
};

} // namespace stardust
} // namespace core

Q_DECLARE_METATYPE(stardust::core::OAISDPlayerCreateRequest)

#endif // OAISDPlayerCreateRequest_H
