/**
 * Stardust API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023-07-25T00:59:12Z
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAISDGameGetResponse_fees_inner.h
 *
 * 
 */

#ifndef OAISDGameGetResponse_fees_inner_H
#define OAISDGameGetResponse_fees_inner_H

#include <QJsonObject>

#include <QString>

#include "OAIEnum.h"
#include "OAIObject.h"

namespace stardust {
namespace core {

class OAISDGameGetResponse_fees_inner : public OAIObject {
public:
    OAISDGameGetResponse_fees_inner();
    OAISDGameGetResponse_fees_inner(QString json);
    ~OAISDGameGetResponse_fees_inner() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    qint32 getFeePercentage() const;
    void setFeePercentage(const qint32 &fee_percentage);
    bool is_fee_percentage_Set() const;
    bool is_fee_percentage_Valid() const;

    QString getFeeType() const;
    void setFeeType(const QString &fee_type);
    bool is_fee_type_Set() const;
    bool is_fee_type_Valid() const;

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();

    qint32 fee_percentage;
    bool m_fee_percentage_isSet;
    bool m_fee_percentage_isValid;

    QString fee_type;
    bool m_fee_type_isSet;
    bool m_fee_type_isValid;
};

} // namespace stardust
} // namespace core

Q_DECLARE_METATYPE(stardust::core::OAISDGameGetResponse_fees_inner)

#endif // OAISDGameGetResponse_fees_inner_H
