/**
 * Stardust API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023-06-15T19:52:41Z
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAISDOrderCreateRequest.h
 *
 * 
 */

#ifndef OAISDOrderCreateRequest_H
#define OAISDOrderCreateRequest_H

#include <QJsonObject>

#include "OAISDOrderCreateTokens.h"
#include <QList>
#include <QString>

#include "OAIEnum.h"
#include "OAIObject.h"

namespace stardust {
namespace core {
class OAISDOrderCreateTokens;

class OAISDOrderCreateRequest : public OAIObject {
public:
    OAISDOrderCreateRequest();
    OAISDOrderCreateRequest(QString json);
    ~OAISDOrderCreateRequest() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    QString getOfferedBy() const;
    void setOfferedBy(const QString &offered_by);
    bool is_offered_by_Set() const;
    bool is_offered_by_Valid() const;

    QList<OAISDOrderCreateTokens> getTokensOffered() const;
    void setTokensOffered(const QList<OAISDOrderCreateTokens> &tokens_offered);
    bool is_tokens_offered_Set() const;
    bool is_tokens_offered_Valid() const;

    QList<OAISDOrderCreateTokens> getTokensRequested() const;
    void setTokensRequested(const QList<OAISDOrderCreateTokens> &tokens_requested);
    bool is_tokens_requested_Set() const;
    bool is_tokens_requested_Valid() const;

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();

    QString offered_by;
    bool m_offered_by_isSet;
    bool m_offered_by_isValid;

    QList<OAISDOrderCreateTokens> tokens_offered;
    bool m_tokens_offered_isSet;
    bool m_tokens_offered_isValid;

    QList<OAISDOrderCreateTokens> tokens_requested;
    bool m_tokens_requested_isSet;
    bool m_tokens_requested_isValid;
};

} // namespace stardust
} // namespace core

Q_DECLARE_METATYPE(stardust::core::OAISDOrderCreateRequest)

#endif // OAISDOrderCreateRequest_H
