/**
 * Stardust API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023-06-15T19:52:41Z
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAISDPlayerMutateRequest.h
 *
 * 
 */

#ifndef OAISDPlayerMutateRequest_H
#define OAISDPlayerMutateRequest_H

#include <QJsonObject>

#include "OAIObject.h"
#include <QString>

#include "OAIEnum.h"
#include "OAIObject.h"

namespace stardust {
namespace core {

class OAISDPlayerMutateRequest : public OAIObject {
public:
    OAISDPlayerMutateRequest();
    OAISDPlayerMutateRequest(QString json);
    ~OAISDPlayerMutateRequest() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    QString getPlayerId() const;
    void setPlayerId(const QString &player_id);
    bool is_player_id_Set() const;
    bool is_player_id_Valid() const;

    OAIObject getProps() const;
    void setProps(const OAIObject &props);
    bool is_props_Set() const;
    bool is_props_Valid() const;

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();

    QString player_id;
    bool m_player_id_isSet;
    bool m_player_id_isValid;

    OAIObject props;
    bool m_props_isSet;
    bool m_props_isValid;
};

} // namespace stardust
} // namespace core

Q_DECLARE_METATYPE(stardust::core::OAISDPlayerMutateRequest)

#endif // OAISDPlayerMutateRequest_H
