/**
 * Stardust API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023-07-25T00:59:12Z
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "OAISDTokenMintBulkTokenObject.h"

#include <QDebug>
#include <QJsonArray>
#include <QJsonDocument>
#include <QObject>

#include "OAIHelpers.h"

namespace stardust {
namespace core {

OAISDTokenMintBulkTokenObject::OAISDTokenMintBulkTokenObject(QString json) {
    this->initializeModel();
    this->fromJson(json);
}

OAISDTokenMintBulkTokenObject::OAISDTokenMintBulkTokenObject() {
    this->initializeModel();
}

OAISDTokenMintBulkTokenObject::~OAISDTokenMintBulkTokenObject() {}

void OAISDTokenMintBulkTokenObject::initializeModel() {

    m_template_id_isSet = false;
    m_template_id_isValid = false;

    m_amount_isSet = false;
    m_amount_isValid = false;

    m_props_isSet = false;
    m_props_isValid = false;

    m_public_metadata_isSet = false;
    m_public_metadata_isValid = false;
}

void OAISDTokenMintBulkTokenObject::fromJson(QString jsonString) {
    QByteArray array(jsonString.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
}

void OAISDTokenMintBulkTokenObject::fromJsonObject(QJsonObject json) {

    m_template_id_isValid = ::stardust::core::fromJsonValue(template_id, json[QString("templateId")]);
    m_template_id_isSet = !json[QString("templateId")].isNull() && m_template_id_isValid;

    m_amount_isValid = ::stardust::core::fromJsonValue(amount, json[QString("amount")]);
    m_amount_isSet = !json[QString("amount")].isNull() && m_amount_isValid;

    m_props_isValid = ::stardust::core::fromJsonValue(props, json[QString("props")]);
    m_props_isSet = !json[QString("props")].isNull() && m_props_isValid;

    m_public_metadata_isValid = ::stardust::core::fromJsonValue(public_metadata, json[QString("publicMetadata")]);
    m_public_metadata_isSet = !json[QString("publicMetadata")].isNull() && m_public_metadata_isValid;
}

QString OAISDTokenMintBulkTokenObject::asJson() const {
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject OAISDTokenMintBulkTokenObject::asJsonObject() const {
    QJsonObject obj;
    if (m_template_id_isSet) {
        obj.insert(QString("templateId"), ::stardust::core::toJsonValue(template_id));
    }
    if (m_amount_isSet) {
        obj.insert(QString("amount"), ::stardust::core::toJsonValue(amount));
    }
    if (props.isSet()) {
        obj.insert(QString("props"), ::stardust::core::toJsonValue(props));
    }
    if (m_public_metadata_isSet) {
        obj.insert(QString("publicMetadata"), ::stardust::core::toJsonValue(public_metadata));
    }
    return obj;
}

qint32 OAISDTokenMintBulkTokenObject::getTemplateId() const {
    return template_id;
}
void OAISDTokenMintBulkTokenObject::setTemplateId(const qint32 &template_id) {
    this->template_id = template_id;
    this->m_template_id_isSet = true;
}

bool OAISDTokenMintBulkTokenObject::is_template_id_Set() const{
    return m_template_id_isSet;
}

bool OAISDTokenMintBulkTokenObject::is_template_id_Valid() const{
    return m_template_id_isValid;
}

QString OAISDTokenMintBulkTokenObject::getAmount() const {
    return amount;
}
void OAISDTokenMintBulkTokenObject::setAmount(const QString &amount) {
    this->amount = amount;
    this->m_amount_isSet = true;
}

bool OAISDTokenMintBulkTokenObject::is_amount_Set() const{
    return m_amount_isSet;
}

bool OAISDTokenMintBulkTokenObject::is_amount_Valid() const{
    return m_amount_isValid;
}

OAISDTokenMintBulkTokenObject_props OAISDTokenMintBulkTokenObject::getProps() const {
    return props;
}
void OAISDTokenMintBulkTokenObject::setProps(const OAISDTokenMintBulkTokenObject_props &props) {
    this->props = props;
    this->m_props_isSet = true;
}

bool OAISDTokenMintBulkTokenObject::is_props_Set() const{
    return m_props_isSet;
}

bool OAISDTokenMintBulkTokenObject::is_props_Valid() const{
    return m_props_isValid;
}

OAIObject OAISDTokenMintBulkTokenObject::getPublicMetadata() const {
    return public_metadata;
}
void OAISDTokenMintBulkTokenObject::setPublicMetadata(const OAIObject &public_metadata) {
    this->public_metadata = public_metadata;
    this->m_public_metadata_isSet = true;
}

bool OAISDTokenMintBulkTokenObject::is_public_metadata_Set() const{
    return m_public_metadata_isSet;
}

bool OAISDTokenMintBulkTokenObject::is_public_metadata_Valid() const{
    return m_public_metadata_isValid;
}

bool OAISDTokenMintBulkTokenObject::isSet() const {
    bool isObjectUpdated = false;
    do {
        if (m_template_id_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_amount_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (props.isSet()) {
            isObjectUpdated = true;
            break;
        }

        if (m_public_metadata_isSet) {
            isObjectUpdated = true;
            break;
        }
    } while (false);
    return isObjectUpdated;
}

bool OAISDTokenMintBulkTokenObject::isValid() const {
    // only required properties are required for the object to be considered valid
    return m_template_id_isValid && m_amount_isValid && true;
}

} // namespace stardust
} // namespace core
