/**
 * Stardust API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023-06-15T19:52:41Z
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAISDTokenMutateRequest.h
 *
 * 
 */

#ifndef OAISDTokenMutateRequest_H
#define OAISDTokenMutateRequest_H

#include <QJsonObject>

#include "OAIObject.h"

#include "OAIEnum.h"
#include "OAIObject.h"

namespace stardust {
namespace core {

class OAISDTokenMutateRequest : public OAIObject {
public:
    OAISDTokenMutateRequest();
    OAISDTokenMutateRequest(QString json);
    ~OAISDTokenMutateRequest() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    qint32 getTokenId() const;
    void setTokenId(const qint32 &token_id);
    bool is_token_id_Set() const;
    bool is_token_id_Valid() const;

    OAIObject getProps() const;
    void setProps(const OAIObject &props);
    bool is_props_Set() const;
    bool is_props_Valid() const;

    OAIObject getPublicMetadata() const;
    void setPublicMetadata(const OAIObject &public_metadata);
    bool is_public_metadata_Set() const;
    bool is_public_metadata_Valid() const;

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();

    qint32 token_id;
    bool m_token_id_isSet;
    bool m_token_id_isValid;

    OAIObject props;
    bool m_props_isSet;
    bool m_props_isValid;

    OAIObject public_metadata;
    bool m_public_metadata_isSet;
    bool m_public_metadata_isValid;
};

} // namespace stardust
} // namespace core

Q_DECLARE_METATYPE(stardust::core::OAISDTokenMutateRequest)

#endif // OAISDTokenMutateRequest_H
