/**
 * Stardust API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023-06-15T19:52:41Z
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAISDTemplateCreateRequest_props.h
 *
 * 
 */

#ifndef OAISDTemplateCreateRequest_props_H
#define OAISDTemplateCreateRequest_props_H

#include <QJsonObject>

#include "OAIObject.h"

#include "OAIEnum.h"
#include "OAIObject.h"

namespace stardust {
namespace core {

class OAISDTemplateCreateRequest_props : public OAIObject {
public:
    OAISDTemplateCreateRequest_props();
    OAISDTemplateCreateRequest_props(QString json);
    ~OAISDTemplateCreateRequest_props() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    OAIObject getImmutable() const;
    void setImmutable(const OAIObject &immutable);
    bool is_immutable_Set() const;
    bool is_immutable_Valid() const;

    OAIObject getRMutable() const;
    void setRMutable(const OAIObject &r_mutable);
    bool is_r_mutable_Set() const;
    bool is_r_mutable_Valid() const;

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();

    OAIObject immutable;
    bool m_immutable_isSet;
    bool m_immutable_isValid;

    OAIObject r_mutable;
    bool m_r_mutable_isSet;
    bool m_r_mutable_isValid;
};

} // namespace stardust
} // namespace core

Q_DECLARE_METATYPE(stardust::core::OAISDTemplateCreateRequest_props)

#endif // OAISDTemplateCreateRequest_props_H
