/**
 * Stardust API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023-07-25T00:59:12Z
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAISDPlayerGetAllResponse.h
 *
 * This is the data output json model
 */

#ifndef OAISDPlayerGetAllResponse_H
#define OAISDPlayerGetAllResponse_H

#include <QJsonObject>

#include <QMap>
#include <QString>

#include "OAIEnum.h"
#include "OAIObject.h"

namespace stardust {
namespace core {

class OAISDPlayerGetAllResponse : public OAIObject {
public:
    OAISDPlayerGetAllResponse();
    OAISDPlayerGetAllResponse(QString json);
    ~OAISDPlayerGetAllResponse() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    QString getPlayerId() const;
    void setPlayerId(const QString &player_id);
    bool is_player_id_Set() const;
    bool is_player_id_Valid() const;

    QString getUniqueId() const;
    void setUniqueId(const QString &unique_id);
    bool is_unique_id_Set() const;
    bool is_unique_id_Valid() const;

    double getId() const;
    void setId(const double &id);
    bool is_id_Set() const;
    bool is_id_Valid() const;

    QString getLastSeen() const;
    void setLastSeen(const QString &last_seen);
    bool is_last_seen_Set() const;
    bool is_last_seen_Valid() const;

    QString getImage() const;
    void setImage(const QString &image);
    bool is_image_Set() const;
    bool is_image_Valid() const;

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();

    QString player_id;
    bool m_player_id_isSet;
    bool m_player_id_isValid;

    QString unique_id;
    bool m_unique_id_isSet;
    bool m_unique_id_isValid;

    double id;
    bool m_id_isSet;
    bool m_id_isValid;

    QString last_seen;
    bool m_last_seen_isSet;
    bool m_last_seen_isValid;

    QString image;
    bool m_image_isSet;
    bool m_image_isValid;
};

} // namespace stardust
} // namespace core

Q_DECLARE_METATYPE(stardust::core::OAISDPlayerGetAllResponse)

#endif // OAISDPlayerGetAllResponse_H
