/**
 * Stardust API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023-06-15T19:52:41Z
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "OAISDPlayerCreateRequest.h"

#include <QDebug>
#include <QJsonArray>
#include <QJsonDocument>
#include <QObject>

#include "OAIHelpers.h"

namespace stardust {
namespace core {

OAISDPlayerCreateRequest::OAISDPlayerCreateRequest(QString json) {
    this->initializeModel();
    this->fromJson(json);
}

OAISDPlayerCreateRequest::OAISDPlayerCreateRequest() {
    this->initializeModel();
}

OAISDPlayerCreateRequest::~OAISDPlayerCreateRequest() {}

void OAISDPlayerCreateRequest::initializeModel() {

    m_unique_id_isSet = false;
    m_unique_id_isValid = false;

    m_image_isSet = false;
    m_image_isValid = false;

    m_user_data_isSet = false;
    m_user_data_isValid = false;
}

void OAISDPlayerCreateRequest::fromJson(QString jsonString) {
    QByteArray array(jsonString.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
}

void OAISDPlayerCreateRequest::fromJsonObject(QJsonObject json) {

    m_unique_id_isValid = ::stardust::core::fromJsonValue(unique_id, json[QString("uniqueId")]);
    m_unique_id_isSet = !json[QString("uniqueId")].isNull() && m_unique_id_isValid;

    m_image_isValid = ::stardust::core::fromJsonValue(image, json[QString("image")]);
    m_image_isSet = !json[QString("image")].isNull() && m_image_isValid;

    m_user_data_isValid = ::stardust::core::fromJsonValue(user_data, json[QString("userData")]);
    m_user_data_isSet = !json[QString("userData")].isNull() && m_user_data_isValid;
}

QString OAISDPlayerCreateRequest::asJson() const {
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject OAISDPlayerCreateRequest::asJsonObject() const {
    QJsonObject obj;
    if (m_unique_id_isSet) {
        obj.insert(QString("uniqueId"), ::stardust::core::toJsonValue(unique_id));
    }
    if (m_image_isSet) {
        obj.insert(QString("image"), ::stardust::core::toJsonValue(image));
    }
    if (m_user_data_isSet) {
        obj.insert(QString("userData"), ::stardust::core::toJsonValue(user_data));
    }
    return obj;
}

QString OAISDPlayerCreateRequest::getUniqueId() const {
    return unique_id;
}
void OAISDPlayerCreateRequest::setUniqueId(const QString &unique_id) {
    this->unique_id = unique_id;
    this->m_unique_id_isSet = true;
}

bool OAISDPlayerCreateRequest::is_unique_id_Set() const{
    return m_unique_id_isSet;
}

bool OAISDPlayerCreateRequest::is_unique_id_Valid() const{
    return m_unique_id_isValid;
}

QString OAISDPlayerCreateRequest::getImage() const {
    return image;
}
void OAISDPlayerCreateRequest::setImage(const QString &image) {
    this->image = image;
    this->m_image_isSet = true;
}

bool OAISDPlayerCreateRequest::is_image_Set() const{
    return m_image_isSet;
}

bool OAISDPlayerCreateRequest::is_image_Valid() const{
    return m_image_isValid;
}

OAIObject OAISDPlayerCreateRequest::getUserData() const {
    return user_data;
}
void OAISDPlayerCreateRequest::setUserData(const OAIObject &user_data) {
    this->user_data = user_data;
    this->m_user_data_isSet = true;
}

bool OAISDPlayerCreateRequest::is_user_data_Set() const{
    return m_user_data_isSet;
}

bool OAISDPlayerCreateRequest::is_user_data_Valid() const{
    return m_user_data_isValid;
}

bool OAISDPlayerCreateRequest::isSet() const {
    bool isObjectUpdated = false;
    do {
        if (m_unique_id_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_image_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_user_data_isSet) {
            isObjectUpdated = true;
            break;
        }
    } while (false);
    return isObjectUpdated;
}

bool OAISDPlayerCreateRequest::isValid() const {
    // only required properties are required for the object to be considered valid
    return m_unique_id_isValid && m_user_data_isValid && true;
}

} // namespace stardust
} // namespace core
