/**
 * Stardust API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023-06-15T19:52:41Z
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "OAISDPlayerMutateRequest.h"

#include <QDebug>
#include <QJsonArray>
#include <QJsonDocument>
#include <QObject>

#include "OAIHelpers.h"

namespace stardust {
namespace core {

OAISDPlayerMutateRequest::OAISDPlayerMutateRequest(QString json) {
    this->initializeModel();
    this->fromJson(json);
}

OAISDPlayerMutateRequest::OAISDPlayerMutateRequest() {
    this->initializeModel();
}

OAISDPlayerMutateRequest::~OAISDPlayerMutateRequest() {}

void OAISDPlayerMutateRequest::initializeModel() {

    m_player_id_isSet = false;
    m_player_id_isValid = false;

    m_props_isSet = false;
    m_props_isValid = false;
}

void OAISDPlayerMutateRequest::fromJson(QString jsonString) {
    QByteArray array(jsonString.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
}

void OAISDPlayerMutateRequest::fromJsonObject(QJsonObject json) {

    m_player_id_isValid = ::stardust::core::fromJsonValue(player_id, json[QString("playerId")]);
    m_player_id_isSet = !json[QString("playerId")].isNull() && m_player_id_isValid;

    m_props_isValid = ::stardust::core::fromJsonValue(props, json[QString("props")]);
    m_props_isSet = !json[QString("props")].isNull() && m_props_isValid;
}

QString OAISDPlayerMutateRequest::asJson() const {
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject OAISDPlayerMutateRequest::asJsonObject() const {
    QJsonObject obj;
    if (m_player_id_isSet) {
        obj.insert(QString("playerId"), ::stardust::core::toJsonValue(player_id));
    }
    if (m_props_isSet) {
        obj.insert(QString("props"), ::stardust::core::toJsonValue(props));
    }
    return obj;
}

QString OAISDPlayerMutateRequest::getPlayerId() const {
    return player_id;
}
void OAISDPlayerMutateRequest::setPlayerId(const QString &player_id) {
    this->player_id = player_id;
    this->m_player_id_isSet = true;
}

bool OAISDPlayerMutateRequest::is_player_id_Set() const{
    return m_player_id_isSet;
}

bool OAISDPlayerMutateRequest::is_player_id_Valid() const{
    return m_player_id_isValid;
}

OAIObject OAISDPlayerMutateRequest::getProps() const {
    return props;
}
void OAISDPlayerMutateRequest::setProps(const OAIObject &props) {
    this->props = props;
    this->m_props_isSet = true;
}

bool OAISDPlayerMutateRequest::is_props_Set() const{
    return m_props_isSet;
}

bool OAISDPlayerMutateRequest::is_props_Valid() const{
    return m_props_isValid;
}

bool OAISDPlayerMutateRequest::isSet() const {
    bool isObjectUpdated = false;
    do {
        if (m_player_id_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_props_isSet) {
            isObjectUpdated = true;
            break;
        }
    } while (false);
    return isObjectUpdated;
}

bool OAISDPlayerMutateRequest::isValid() const {
    // only required properties are required for the object to be considered valid
    return m_player_id_isValid && m_props_isValid && true;
}

} // namespace stardust
} // namespace core
