/**
 * Stardust API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023-06-15T19:52:41Z
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAISDTokenBurnRequest.h
 *
 * 
 */

#ifndef OAISDTokenBurnRequest_H
#define OAISDTokenBurnRequest_H

#include <QJsonObject>

#include "OAISDTokenBurnRequest_tokenObjects_inner.h"
#include <QList>
#include <QString>

#include "OAIEnum.h"
#include "OAIObject.h"

namespace stardust {
namespace core {
class OAISDTokenBurnRequest_tokenObjects_inner;

class OAISDTokenBurnRequest : public OAIObject {
public:
    OAISDTokenBurnRequest();
    OAISDTokenBurnRequest(QString json);
    ~OAISDTokenBurnRequest() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    QString getPlayerId() const;
    void setPlayerId(const QString &player_id);
    bool is_player_id_Set() const;
    bool is_player_id_Valid() const;

    QList<OAISDTokenBurnRequest_tokenObjects_inner> getTokenObjects() const;
    void setTokenObjects(const QList<OAISDTokenBurnRequest_tokenObjects_inner> &token_objects);
    bool is_token_objects_Set() const;
    bool is_token_objects_Valid() const;

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();

    QString player_id;
    bool m_player_id_isSet;
    bool m_player_id_isValid;

    QList<OAISDTokenBurnRequest_tokenObjects_inner> token_objects;
    bool m_token_objects_isSet;
    bool m_token_objects_isValid;
};

} // namespace stardust
} // namespace core

Q_DECLARE_METATYPE(stardust::core::OAISDTokenBurnRequest)

#endif // OAISDTokenBurnRequest_H
